name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4.1.1
        with:  # no need for the history
          fetch-depth: 1
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: uv pip install --system --pre -e ".[test]"
      - name: Test with pytest
        run: uv run pytest pydra_ml/tests/test_classifier.py -s
